// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjmN7P-3Knxqc_AmOCk6vNwxmSPtEL6nc',
    appId: '1:114133901378:web:d9001774a307bc737ccddb',
    messagingSenderId: '114133901378',
    projectId: 'young-sq-c01df',
    authDomain: 'young-sq-c01df.firebaseapp.com',
    storageBucket: 'young-sq-c01df.appspot.com',
    measurementId: 'G-D7XL47WVLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGzw4TffDXLPuvS9_nyAyBTDMxTATkz30',
    appId: '1:114133901378:android:e4e84da891ffddcc7ccddb',
    messagingSenderId: '114133901378',
    projectId: 'young-sq-c01df',
    storageBucket: 'young-sq-c01df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7plA9-R4c1EvR6SG6PQb4GiqMHmpwiLo',
    appId: '1:114133901378:ios:a53461e748ba3d457ccddb',
    messagingSenderId: '114133901378',
    projectId: 'young-sq-c01df',
    storageBucket: 'young-sq-c01df.appspot.com',
    iosBundleId: 'com.example.youngSquad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7plA9-R4c1EvR6SG6PQb4GiqMHmpwiLo',
    appId: '1:114133901378:ios:a53461e748ba3d457ccddb',
    messagingSenderId: '114133901378',
    projectId: 'young-sq-c01df',
    storageBucket: 'young-sq-c01df.appspot.com',
    iosBundleId: 'com.example.youngSquad',
  );
}
